spring:
  application:
    name: BankingApplication
  datasource:
    url: jdbc:mysql://localhost:3306/banking_app
    username: root
    password: Minhduc3
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenminhduc02042004@gmail.com
    password: hxgz llhs chcj nivz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 2004

jwtSecretString: OmMiNRXAJdZYS6QI8A0saFBHlRiKA06trwRy73VAZTg0F9mUN710AYKJlHvMS0qwNruNm5AHyKC5uizR92OJ7GeorfmFjHvC44ZbHqVbB3YqeavwEHSoWoii0AEFQRgm

currencyApiKey: ${CURRENCY_API_KEY:cur_live_4w6LyLYDl1zZhRblhAX5TS4DtuXTGeQPiMtwqZMZ}

openai.model: meta-llama/llama-4-maverick:free
openai.api.key: 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
openai.api.url: https://openrouter.ai/api/v1/chat/completions

cloud.name: dcfmbv2yz
api.key: 756826661271172
api.secret: hnSKd18j9mH8zLUY0wbItTI5ZDM